import type { Project } from '@/types';

export const PROJECTS: Project[] = [
  {
    id: '01',
    name: 'Quickserve',
    type: 'Logistics SaaS',
    status: 'Acquisition Open',
    description: 'High-performance delivery and logistics architecture built for zero-latency dispatching and fleet management.',
    tech: ['Next.js', 'WebSockets', 'PostgreSQL'],
    image: '/images/projects/quickserve.jpg',
    link: 'https://quickserve.vercel.app',
  },
  {
    id: '02',
    name: 'TrustRelay',
    type: 'Fintech Core Protocol',
    status: 'Operational',
    description: 'Secure, high-frequency financial transaction relayer designed with enterprise-grade encryption.',
    tech: ['React', 'Node.js', 'Redis'],
    image: '/images/projects/trustrely.jpg',
    link: 'https://trustrely.vercel.app',
  },
  {
    id: '03',
    name: 'Wedding-OS',
    type: 'Event Ecosystem',
    status: 'Seeking Partner',
    description: 'Comprehensive digital operating system for high-end event management, guest tracking, and vendor coordination.',
    tech: ['Next.js', 'Tailwind CSS', 'Prisma'],
    image: '/images/projects/wedding-os.jpg',
    link: 'https://wedding-os.vercel.app',
  },
  {
    id: '04',
    name: 'Al-Kawthar',
    type: 'Digital Quran',
    status: 'Deployed',
    description: 'A highly optimized, accessible digital Quran application engineered for seamless reading and global reach.',
    tech: ['React Native', 'API Integrations'],
    image: '/images/projects/al-kawthar.jpg',
    link: 'https://al-kawthar.vercel.app',
  },
  {
    id: '05',
    name: 'Dispatchr',
    type: 'Fleet Management',
    status: 'Deployed',
    description: 'Real-time routing and dispatching system optimized for complex supply chain logistics.',
    tech: ['React', 'Maps API', 'Node.js'],
    image: '/images/projects/dispatchr.jpg',
    link: 'https://dispatchr.vercel.app',
  },
  {
    id: '06',
    name: 'BABA-K TicketHub',
    type: 'Ticketing Platform',
    status: 'Deployed',
    description: 'Seamless event ticketing and booking system with real-time inventory management and secure payment processing.',
    tech: ['Next.js', 'Stripe', 'PostgreSQL'],
    image: '/images/projects/baba-k-tickethub.jpg',
    link: 'https://baba-k-tickethub.vercel.app',
  },
  {
    id: '07',
    name: 'Five Ways International School',
    type: 'EdTech Platform',
    status: 'Deployed',
    description: 'Digital learning ecosystem for institutional management, student engagement, and academic excellence.',
    tech: ['Next.js', 'React', 'Firebase'],
    image: '/images/projects/five-ways-intl-sch.jpg',
    link: 'https://five-ways-intl-sch.vercel.app',
  },
  {
    id: '08',
    name: 'Daily Motivational Quote',
    type: 'Wellness App',
    status: 'Deployed',
    description: 'Inspirational daily quotes platform delivering personalized motivation with sharing and collection features.',
    tech: ['React', 'Next.js', 'API'],
    image: '/images/projects/daily-motivational-quote.jpg',
    link: 'https://daily-motivational-quote.vercel.app',
  },
  {
    id: '09',
    name: 'Autofest International Driftmaster',
    type: 'Event Platform',
    status: 'Deployed',
    description: 'High-octane motorsports event platform featuring live tracking, competitor standings, and fan engagement.',
    tech: ['Next.js', 'WebSockets', 'React'],
    image: '/images/projects/autofest-driftmaster.jpg',
    link: 'https://www.autofestinternational.com',
  },
  {
    id: '10',
    name: 'TradeExpo',
    type: 'B2B Commerce',
    status: 'Deployed',
    description: 'Enterprise trade exposition platform connecting global buyers and sellers with advanced search and marketplace features.',
    tech: ['Next.js', 'Node.js', 'PostgreSQL'],
    image: '/images/projects/tradeexpo.jpg',
    link: 'https://tradeexpo.vercel.app',
  },
  {
    id: '11',
    name: 'Beacon Hub',
    type: 'Content Engine',
    status: 'Deployed',
    description: 'Centralized content distribution and management platform with real-time analytics and audience engagement tools.',
    tech: ['React', 'Node.js', 'MongoDB'],
    image: '/images/projects/beacon-hub.jpg',
    link: 'https://www.beacon-hub.com.ng',
  },
];

export const HOMEPAGE_PROJECTS = [
  { name: 'TrustRelay', type: 'Fintech Core', status: 'Deployed' },
  { name: 'Quickserve', type: 'Logistics SaaS', status: 'Deployed' },
  { name: 'Wedding-OS', type: 'Event Ecosystem', status: 'Venture' },
  { name: 'Dispatchr', type: 'Fleet Management', status: 'Deployed' },
  { name: 'Al-Kawthar', type: 'Digital Quran', status: 'Deployed' },
  { name: 'BABA-K TicketHub', type: 'Ticketing Platform', status: 'Deployed' },
  { name: 'Five Ways International School', type: 'EdTech Platform', status: 'Deployed' },
  { name: 'Daily Motivational Quote', type: 'Wellness App', status: 'Deployed' },
  { name: 'Autofest International Driftmaster', type: 'Motorsports Event', status: 'Deployed' },
  { name: 'TradeExpo', type: 'B2B Commerce', status: 'Deployed' },
  { name: 'Beacon Hub', type: 'Content Engine', status: 'Deployed' },
];
